# Generated by Django 4.2.16 on 2025-01-07 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.CharField(blank=True, max_length=12, null=True)),
                ('Date', models.DateField()),
                ('Paymentmethod', models.CharField(choices=[('googlepay', 'Googlepay'), ('phonepe', 'Phonepe'), ('upi', 'Upi')], default='upi', max_length=10)),
                ('Investment', models.IntegerField(choices=[(200, '200'), (500, '500'), (1000, '1000')], default=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proscheme_app.items')),
            ],
        ),
    ]
