# Generated by Django 4.2.16 on 2025-01-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proscheme_app', '0002_productscheme_remove_trans_trans_number_delete_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscheme',
            options={'verbose_name': 'Product Scheme', 'verbose_name_plural': 'Product Schemes'},
        ),
    ]
