# Generated by Django 4.2.16 on 2025-01-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proscheme_app', '0003_alter_productscheme_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscheme',
            options={},
        ),
    ]
